import "./globals.css";

export const metadata = {
  title: "StreamUi || Copy Paste Components",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body className="font-poppins bg-gray-100">
        {children}
      </body>
    </html>
  );
}